// a03-react-host-2-top-await/src/components/App.tsx
import React from 'react';
import loadComponent from './loadComponent';
// console.log(MyModel);
// const { default: SimpleModel } = await loadComponent('app1', './SimpleModel');
const { default: SimpleModel } = await import('app1/SimpleModel');
const { default: useCounter } = await import('app1/useCounter');
const { default: Header } = await import('app1/Header');
console.log(useCounter);
console.log(SimpleModel);

const App:React.FC = () => {
  // const [count, setCount] = React.useState(0);
  const {
    count,
    increment,
  } = useCounter();
  return (
    <div>
      <h1>{count}</h1>
      <button onClick={increment}>increment</button>
      <Header />
    </div>
  );
};

export default App;

// b02-host-vue/src/App.vue
<script>
import { defineAsyncComponent } from 'vue';
import MyModel from 'app1/MyModel';
import Button from 'app1/Button';

const RemoteHeader = defineAsyncComponent(() => import('app1/Header'));

export default {
  components: {
    RemoteHeader,
    Button,
  },
  data() {
    return {
      name: 'default',
    };
  },
  mounted() {
    console.log(MyModel);
    this.name = MyModel.name;
  },
};
</script>

<template>
  <div id="app">
    <RemoteHeader />
    <RemoteHeader :init-value="10" />
    <Button />
    <h1>name:{{ name }}</h1>
  </div>
</template>
