// 03-host-umd/src/components/App.jsx
import React, { useState } from 'react';
import SystemComponent from './SystemComponent'
import loadComponent from './loadComponent';
import MyModel from 'app1/MyModel';

console.log(MyModel);

export default () => {
  const [count, setCount] = React.useState(0)
  return (
    <div>
      <h1>UMD, {count}</h1>
      <button onClick={()=> setCount(count + 1)}>increment</button>
      <SystemComponent module="Header" initCount={10} />
      <SystemComponent module="Footer" />
    </div>
  );
}

// b02-host-vue/src/App.vue
<script>
import { defineAsyncComponent } from 'vue';
import MyModel from 'app1/MyModel';
import Button from 'app1/Button';

const RemoteHeader = defineAsyncComponent(() => import('app1/Header'));

export default {
  components: {
    RemoteHeader,
    Button,
  },
  data() {
    return {
      name: 'default',
    };
  },
  mounted() {
    console.log(MyModel);
    this.name = MyModel.name;
  },
};
</script>

<template>
  <div id="app">
    <RemoteHeader />
    <RemoteHeader :init-value="10" />
    <Button />
    <h1>name:{{ name }}</h1>
  </div>
</template>
