// b02-host-vue/src/App.vue
<script>
import { defineAsyncComponent } from 'vue';
import MyModel from 'app1/MyModel';
import Button from 'app1/Button';

const RemoteHeader = defineAsyncComponent(() => import('app1/Header'));

export default {
  components: {
    RemoteHeader,
    Button,
  },
  data() {
    return {
      name: 'default',
    };
  },
  mounted() {
    console.log(MyModel);
    this.name = MyModel.name;
  },
};
</script>

<template>
  <div id="app">
    <RemoteHeader />
    <RemoteHeader :init-value="10" />
    <Button />
    <h1>name:{{ name }}</h1>
  </div>
</template>

// 02-host/src/components/App.jsx
import React from 'react';
import RemoteHeader from './RemoteHeader';

import MyModel from 'app1/MyModel';
import Header from 'app1/Header';
import useCounter from 'app1/useCounter';
import { NameContextProvider } from "app1/NameContextProvider";


export default () => {
  const [count, setCount] = useCounter();
  const increment = React.useCallback(() => {
    setCount( prev=> prev + 1);
  }, []);
  const value = {
    count,
    setCount,
    increment,
  }
  return (
    <NameContextProvider.Provider value={value}>
      <div>
        <h1>Host {count}</h1>
        <button onClick={()=> setCount(count + 1)}>increment</button>
        {/* <Header /> */}
        <RemoteHeader />
      </div>
    </NameContextProvider.Provider>
  );
}
