// a03-react-host-2-top-await/src/components/App.tsx
import React from 'react';
import loadComponent from './loadComponent';
// console.log(MyModel);
// const { default: SimpleModel } = await loadComponent('app1', './SimpleModel');
const { default: SimpleModel } = await import('app1/SimpleModel');
const { default: useCounter } = await import('app1/useCounter');
const { default: Header } = await import('app1/Header');
console.log(useCounter);
console.log(SimpleModel);

const App:React.FC = () => {
  // const [count, setCount] = React.useState(0);
  const {
    count,
    increment,
  } = useCounter();
  return (
    <div>
      <h1>{count}</h1>
      <button onClick={increment}>increment</button>
      <Header />
    </div>
  );
};

export default App;

// b01-remote-vue/src/App.vue
<script>
import Header from './components/Header.vue';
import Button from './components/Button';

export default {
  components: {
    Header,
    Button,
  },
  data() {
    return {
      value: 0,
    };
  },
  watch: {
    value(newValue) {
      console.log(newValue);
    },
  },
};
</script>

<template>
  <div id="app">
    <Header />
    <Button
      data-name="MyButton"
      @click="value++"
    />
    <h1>value:{{ value }}</h1>
  </div>
</template>
